CREATE DATABASE IF NOT EXISTS dbluumina
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE dbluumina;

CREATE TABLE tipoUsuario (
    idTipo INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    idTipo INT NOT NULL,
    FOREIGN KEY (idTipo) REFERENCES tipoUsuario(idTipo)
);


